- apps/native/screens/LoginScreen.tsx
- apps/native/screens/SignupScreen.tsx
Added error message, made navigation to profile page upon successful signup
> GD - Enhance Login/Signup page 

- apps/native/components/Navbar.tsx
- apps/native/cypress/e2e/propertymanagementscreen.cy.ts
- apps/native/cypress/e2e/userprofile.cy.ts
- apps/native/screens/HomeScreen.tsx
- apps/native/screens/LoginScreen.tsx
- apps/native/screens/PropertyManagementScreen.tsx
- apps/native/screens/UserProfileScreen.tsx
> 80% Coverage on PropertyManagementScreen and UserProfile

- apps/native/app.json
- apps/native/package.json
- apps/native/screens/UserProfileScreen.tsx
- package-lock.json
- package.json
It works but it doesn't support the HEIC image format.
> Fix Profile Picture

- apps/native/components/CondoProfileComponent.tsx
- apps/native/components/EmployeeList.tsx
This is the isolated component for creating employee profiles. There is still the display of the employee list to do. 
How it works:
Modal creates an account with the email and password given as a Employee role with a parameter for the specific job they will be doing (auth + users collection). A reference of the user is also added to a nested collection of employees in the property.
> Lv employee registration component

- apps/native/App.tsx
- apps/native/components/CondoUnitRegistrationComponent.tsx
- apps/native/components/PropertyProfileComponent.tsx
- apps/native/components/UserPropertyForm.tsx
- apps/native/package.json
- apps/native/screens/CondoUnitRegistrationScreen.tsx
- apps/native/screens/PropertyManagementScreen.tsx
- package-lock.json
- package.json
Registration Keys achieve the following:
- Management companies may send registration keys to users by writing their email in the textbox under their property, selecting if they are an owner or renter, and pressing Send Registration Key.
- The user can enter their registration key and if it matches what's on the db, and the emails match, it will change the isUsed attribute to true.
- If a management company needs to resend a key, it will replace the existing key and email.
New files added:
CondoUnitRegistrationComponent.tsx
UserPropertyForm.tsx
CondoUnitRegistrationScreen.tsx
Files Changed:
App.tsx
PropertyProfileComponent.tsx // Will need to be changed to the Condo Unit Component
What else needs to be done:
- Once a management company condo unit screen is created, I will move all the …
> Registration Key function

- apps/native/App.tsx
- apps/native/screens/CondoPaymentFeeStatusAndHistoryScreen.tsx
- apps/native/screens/CondoUnitDescriptionScreen.tsx
- apps/native/screens/index.tsx
Related to https://app.clickup.com/t/86azdbnqw
Added a button to the condo description to get to the fees associated with that condo:
Added a new screen that allows owners to view their payment fees and payment history for a specific condo:
> Payment Fee Status and History Screen

- apps/native/components/AddCondoProfileProperty.tsx
- apps/native/components/AddCondoUnitInformation.tsx
- apps/native/cypress/e2e/userprofile.cy.ts
- apps/native/screens/UserProfileScreen.tsx
The existing unit tests from last sprint stopped working since the ids were overridden, and so I fixed up the existing tests so that they pass.
> Fixed existing unit tests

- apps/web/app/dashboard/page.tsx
- apps/web/app/login/page.tsx
- apps/web/app/properties/page.tsx
- package-lock.json
- packages/ui/src/DashboardNav.tsx
- packages/ui/src/Footer.tsx
- packages/ui/src/LandingPageButton.tsx
- packages/ui/src/Navbar.tsx
- packages/ui/src/NotificationsModal.tsx
- packages/ui/src/Response.tsx
- packages/ui/src/UserProfileModal.tsx
- packages/ui/src/auth/SignIn.tsx
- packages/ui/src/auth/SignUp.tsx
- packages/ui/src/constants/index.tsx
This is in a logical sense a simple PR. 
Refactored the entire web app by removing whitespaces/comments, separated long functions into multiple ones. Added comments where necessary.
> [WEB] Refactoring web app

- apps/native/components/FirebaseFunctions.tsx
- apps/native/cypress/e2e/SignIn/missingInputs.cy.ts
- apps/native/cypress/e2e/SignIn/signIn.cy.ts
- apps/native/cypress/e2e/SignUp/accountCreations.cy.ts
- apps/native/screens/LoginScreen.tsx
- apps/native/screens/SignupScreen.tsx
Managed to get > 80% coverage for signup and login screens. Also extracted a function shared by login and signup screens and stored in a file for common firebase functions.
> PR for refactor and Code coverage

- apps/native/components/AddCondoProfileProperty.tsx
- apps/native/components/AddCondoUnitInformation.tsx
- apps/native/components/AddEmployeeModal.tsx
- apps/native/components/CondoUnitRegistrationComponent.tsx
- apps/native/components/EmployeeListModal.tsx
- apps/native/components/Navbar.tsx
- apps/native/components/PropertyAdapter.tsx
- apps/native/components/UserPropertyForm.tsx
- apps/native/components/button.tsx
Related to task: https://app.clickup.com/t/86azt325t
In this pull request, a systematic refactoring and documentation effort was undertaken across the mobile application's components. The focus was on enhancing code readability and maintainability, with specific attention to optimizing performance and standardizing coding practices. Complex logic was simplified, variable naming was improved for clarity, and consistent coding conventions were applied throughout. Comprehensive documentation comments were added to functions and components to clearly outline their purpose, parameters, and outputs, facilitating better understanding and navigation of the codebase for developers. This refactoring and documentation initiative is intended to improve the development experience and contribute to a …
> Refactor native components

- apps/native/components/PropertyProfileComponent.tsx
- apps/native/screens/CondoPaymentFeeStatusAndHistoryScreen.tsx
- apps/native/screens/CondoUnitDescriptionScreen.tsx
- apps/native/screens/CondoUnitRegistrationScreen.tsx
- apps/native/screens/NotificationsScreen.tsx
- apps/native/screens/UserProfileScreen.tsx
Related to task: https://app.clickup.com/t/86azt325t
In this pull request, I conducted a thorough refactoring and documentation update across all React Native screens in the application. The focus was on enhancing code readability and maintainability by adding descriptive comments, optimizing the use of React hooks, and ensuring consistent error handling and state management practices. This effort aimed to simplify future development and debugging, making the codebase more accessible to new and existing developers. The changes are aligned with best coding practices, contributing to the overall stability and scalability of the project.
> Refactor native screens

- apps/native/components/PropertyProfileComponent.tsx
Related to: [BUGS]: 
In this PR, I've addressed a syntax error within the PropertyProfileComponent that was previously causing compilation issues.
> EmployeeListModal syntax error bug fix

- apps/native/components/PropertyProfileComponent.tsx
- apps/native/cypress/e2e/CondoPaymentFeeStatusAndHistoryScreen.cy.ts
- apps/native/cypress/e2e/condounitdescriptionscreen.cy.ts
- apps/native/screens/CondoPaymentFeeStatusAndHistoryScreen.tsx
- apps/native/screens/CondoUnitDescriptionScreen.tsx
Added unit tests for the contributions I made over sprint 3, these being the CondoUnitDescriptionScreen as well as the  PaymentFeeStatusAndHistoryScreen.
> Added Tests for Condo Unit Description Screen and Condo Payment Fee Status and History Screen

- apps/native/App.tsx
- apps/native/components/AddFacilities.tsx
- apps/native/components/PropertyProfileComponent.tsx
- apps/native/package.json
- apps/native/screens/FacilityBookingScreen.tsx
- apps/native/screens/index.tsx
- package-lock.json
ClickUp user story: https://app.clickup.com/t/86azdbnx0
Description:
This pull request introduces a streamlined update to the facility booking system, enhancing user interaction and backend data management. With a focus on simplicity and efficiency, this feature provides a clear and intuitive interface for users to book facilities within their properties, supported by real-time updates and robust data handling through Firebase Firestore.
Key Features:
Dynamic Facility Display: Showcases facilities with operational hours and color-coded availability.
Interactive Date and Time Selection: Users can easily pick dates and available time slots, with immediate visual feedback on slot status.
Instant Booking Confirmation: Immediate alerts for successful bookings and clear notifications for …
> Added the facility reservation feature

- .gitignore
- apps/web/.gitignore
- apps/web/cypress/e2e/SignIn/signIn.cy.ts
- apps/web/cypress/e2e/SignUp/accountCreations.cy.ts
- apps/web/package.json
https://app.clickup.com/t/86azt91va
This PR has been created in order to fix and add tests to the pipeline for Cypress
> [WEB] Fix cypress tests failing

- apps/web/app/properties/page.tsx
- apps/web/cypress/e2e/properties/propertyCreation.cy.ts
- packages/ui/src/index.tsx
- packages/ui/src/properties/CreatePropertyModal.tsx
- packages/ui/src/properties/CreateUnitModal.tsx
- packages/ui/src/properties/PropertyList.tsx
- User Story: [[Web] Condo management companies can create a profile for a property under their management](https://app.clickup.com/t/86azdbp0f)
This PR adds the feature to create properties for Condo Management Companies.
- Uploads properties and their unit's data to Firebase.
- Shows **mandatory point** that companies need to fill.
- Displays alerts to show the process that is advancing.
- **User-friendly design** shows form clearly.
https://github.com/XavierGuertin/CondoVision/assets/90948686/5b235b44-a7eb-43d6-8fa7-c4bccce06ecf
- Code is cleaner and well-explained.
- Added tests for:
- Having the "Add Property" button only if the user has a userRole of "Condo Management Company".
- There is an alert after creating a property.
- The process of adding a company is fully completed.
The …
> [WEB] Condo management companies can create a profile for a property under their management

- apps/native/components/AddCondoUnitInformation.tsx
Just added another field upon creation of a condo unit that states whether it has been payed this month or not.
> [86aztjcv3] Added New Field "isPayed" When Condo is Created

- apps/native/cypress/e2e/userprofile.cy.ts
The unit test used to take approximately 1 min 41 sec to run to completion. After removing many of the wait() commands and reducing the time during the timeouts, the tests now run in approximately 21 sec
> [86azrkcgh] Refactored userprofile unit test to run faster

- apps/web/app/index.css
- packages/ui/src/DashboardNav.tsx
- packages/ui/src/NotificationsModal.tsx
- packages/ui/src/Requests/RequestBoxForManagement.tsx
- packages/ui/src/Requests/RequestsModal.tsx
Click up link: https://app.clickup.com/t/86azdbnwe
https://github.com/XavierGuertin/CondoVision/assets/36805808/5fb608eb-d324-4125-98d7-0454b155d932
The goal of this user story is to develop a feature that benefits both the user and the condo management company. Here's a breakdown of the process:
1. A user can submit a request linked to a condo unit they own. Once submitted, the request's status becomes "created" and it awaits a response from the condo management company.
2. Only the management company that owns the property associated with the requested condo unit can view the submitted request.
3. The management company has the option to either accept or reject the request. Regardless of the decision, they must provide a response message.
4. After the request has been either accepted or …
> [CV-408] [Web] Condo owners can submit requests

- apps/web/app/properties/page.tsx
- apps/web/cypress/e2e/properties/facilityBooking.cy.ts
- package-lock.json
- package.json
- packages/ui/src/index.tsx
- packages/ui/src/properties/FacilityBookingPage.tsx
- packages/ui/src/properties/PropertyComponent.tsx
- User Story: [[Web] Users can reserve common facilities](https://app.clickup.com/t/86azdbnt5)
Developed a feature where users can reserve facilities for a specific time and date.
- Integrated the new component into the web app, enabling access from the property details page and styled it with Tailwind CSS for a modal presentation.
- Implemented Firebase operations to fetch and update facility availability based on user selections.
https://github.com/XavierGuertin/CondoVision/assets/70493307/e07d2d71-b668-49ed-b22a-88e2f3d36bf5
Added tests for:
- the booking process
- facility selection (time and date)
- booking confirmation alert
Refactored the page.tsx in the web/properties folder so it can have a facilitybooking pop up page
> [CV-406] [Web] Users can reserve common facilities

- packages/ui/src/properties/AddFacilitiesModal.tsx
- packages/ui/src/properties/PropertyComponent.tsx
* ClickUp link: https://app.clickup.com/t/86azdbp0v
This pull request introduces the "Add Facility" feature to our property management application, allowing property managers to easily add new facilities to their properties directly from the UI. We've implemented a modal component that pops up when the "Add Facility" button is clicked, offering a user-friendly form to input the facility name, opening time, and closing time. This enhancement is part of our ongoing efforts to streamline property management operations and improve the user experience.
1. AddFacilityModal Component: Created a new AddFacilityModal component that renders a form within a modal dialog. This component is responsible for capturing new facility data and updating Firestore.
2. PropertyComponent Adjustments: Updated …
> [CV-415] Implement Add Facility Modal in Property Management UI

- apps/native/components/CondoUnitAdapter.tsx
- apps/native/screens/PropertyManagementScreen.tsx
- apps/web/app/properties/page.tsx
- packages/ui/src/finance/DefaultFinanceCard.tsx
- packages/ui/src/properties/PropertyComponent.tsx
- packages/ui/src/properties/PropertyList.tsx
Clickup Issue: https://app.clickup.com/t/86azdbnxu
Added the Financial Payment status and History into the web.
Also added the condo units into each property.
Before clicking on a condo unit:
After clicking on a condo unit:
> [CV-421] Added Financial Status to Web

- apps/native/components/CondoUnitRegistrationComponent.tsx
- apps/native/components/PropertyProfileComponent.tsx
- apps/native/components/UserCondoUnitsList.tsx
- apps/native/components/UserPropertyForm.tsx
- apps/native/screens/CondoUnitDescriptionScreen.tsx
- apps/native/screens/CondoUnitRegistrationScreen.tsx
ClickUp Issue: https://app.clickup.com/t/86b00wy9e
- Condo unit owners/renters are able to view the condos that they own/rent
- Can view necessary information like unit number and condo unit id
- Users may view their registered properties
Updated version of the condo unit registration screen
> [CV-429] Dynamic user condo unit display

- apps/native/App.tsx
- apps/native/screens/NotificationsScreen.tsx
Notification Center for mobile. Exactly the same logic as the web's version.
Retrieve the user's notification collection. Outputs all the notification is the notification screen.
In this screen, you have access to clear the notification which will remove the notification from the array of notifications. It will also update the document in firebase and update the "markAsRead" parameter to true. Only notifications with "markAsRead" = false appear.
On this screen, users also have access to request that they have sent to management companies for a specific house they own or rent. More over, user can submit requests through this very screen. When a request is accepted or rejected, the user can then delete the request from his screen.
https://github.com/XavierGuertin/CondoVision/assets/36805808/ …
> [CV-409][Mobile] User Notification Center

- apps/native/components/AddFacilities.tsx
- apps/native/cypress/e2e/addFacility.cy.ts
https://app.clickup.com/t/86azuehe5
Added Ids to certain elements to facilitate testing
Created cypress tests to ensure proper interactions and behaviour 
Screenshot of successful test run:
> [CV-419][Web/Mobile] Refactoring - Added Cypress Tests for Add Facility Modal

- apps/web/cypress/e2e/properties/addingemployee.cy.ts
- packages/ui/src/properties/AddEmployeeModalWeb.tsx
- packages/ui/src/properties/EmployeeListModalWeb.tsx
- packages/ui/src/properties/PropertyComponent.tsx
ClickUp link: [[CV-413][Web] Condo management companies can set up different roles for different employees](https://app.clickup.com/t/86azdbnzh)
Developed a feature to add employees to a property within the web application.
- Integrated the AddEmployeeModalWeb component into the web app, accessible from the property details page.
- Styled the modal presentation using Tailwind CSS for consistency with the application's design.
- Utilized Firebase authentication and Firestore database for managing employee data securely.
https://github.com/XavierGuertin/CondoVision/assets/70493307/0dad8103-1087-4612-9edb-1e340a8d769a
Implemented tests for:
- Adding a new employee
- Validating employee input fields
- Confirmation alert upon successful employee addition
Refactored the PropertyComponent page …
> [CV-413][Web] Condo management companies can set up different roles for different employees

- apps/native/App.tsx
- apps/native/components/FirebaseFunctions.tsx
- apps/native/screens/NotificationsManagementScreen.tsx
- apps/native/screens/NotificationsScreen.tsx
- apps/native/screens/NotificationsScreenUser.tsx
- apps/native/screens/PropertyManagementScreen.tsx
- apps/native/screens/UserProfileScreen.tsx
- apps/native/screens/index.tsx
The goal of this user story is to develop a feature that benefits both the user and the condo management company. Here's a breakdown of the process:
1. A user can submit a request linked to a condo unit they own. Once submitted, the request's status becomes "created" and it awaits a response from the condo management company.
2. Only the management company that owns the property associated with the requested condo unit can view the submitted request.
3. The management company has the option to either accept or reject the request. Regardless of the decision, they must provide a response message.
4. After the request has been either accepted or rejected, the user will be notified of the status change and can view the management company's response message.
5. If desired, the user has the …
> [CV-410] - [Mobile] Condo owners can submit requests

- apps/native/components/UserPropertyForm.tsx
Clickup Link: https://app.clickup.com/t/86azdbp14
Quick changes to display the registration key to the management company.
> Display Registration Key 

- apps/web/app/properties/page.tsx
- packages/ui/src/DashboardNav.tsx
- packages/ui/src/finance/DefaultCondoFeeCalcCard.tsx
- packages/ui/src/index.tsx
- packages/ui/src/properties/PropertyComponent.tsx
- packages/ui/src/properties/PropertyList.tsx
**Click up Issue:** https://app.clickup.com/t/86azdbnzc
This PR integrates the DefaultCondoFeeCalcCard into the PropertyComponent. With this update, the Condo Fee Calculation feature will be displayed alongside the Finance Status when a unit is selected within a property. Here's the user flow:
- A user clicks on a property.
- Upon selecting a unit within that property, both the Finance Status and the Condo Fee Calculation will appear concurrently.
This revision ensures both a smoother transition between descriptions and clearer communication of how the changes affect user interaction.
> [CV-420][Web] Condo Fee Calculation

- apps/native/components/FirebaseFunctions.tsx
- apps/native/screens/PropertyManagementScreen.tsx
> [CV-512] - Fix Issue With AsyncStorage
